apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panlong.fullname" . }}
  labels:
    {{- include "panlong.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "panlong.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "panlong.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: aliyun
      serviceAccountName: {{ include "panlong.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: ENV_MONGO_DBNAME
              value: database
            - name: ENV_MONGO_HOST
              value: 10.43.181.16
            - name: ENV_MONGO_PASSWORD
              value: gOBddXPLur@ghwnz}
            - name: ENV_MONGO_PORT
              value: "27017"
            - name: ENV_MONGO_USER
              value: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
